### ISSUE TITLE
Art cover size

### ISSUE THREAD

**Issue by atarbig** [Marekkon5/beatporttagger#17]
1.1.8 - cover art 1400 size only, i set 500 but get 1400 always.
And
I noticed that tracks with the sticker on the covers of "Exclusive" "Hype" are not found. It may be a match but check if it affects the search. For instance tracks from these releases not found an have "exclusive" mark
I send several links of tracks "exclusive" and "hype" for check.
Here links not found tracks (in releases):
https://www.beatport.com/release/from-outer-space/3254592
https://www.beatport.com/release/the-rituals/3232540
https://www.beatport.com/release/zion-ep/3257297
https://www.beatport.com/release/crisis/3234220
https://www.beatport.com/release/the-sound-of-2021-sampler-1/3271131
https://www.beatport.com/release/i-dont-blame-you/3206091

here several tracks with mark "exclusive" and "hype"
https://www26.zippyshare.com/v/ENdiOKxD/file.html
I know that beatport broke the api, just check

**Comment by bascurtiz** [comment]
@atarbig 
Regarding not found:
Can you check again?
I think they've changed/fixed something, cause I can find all your examples:
https://www.beatport.com/search?q=jay+lumen+from+outer+space
https://www.beatport.com/search?q=joe+de+renzo+the+rituals
https://www.beatport.com/search?q=k-mack+zion
https://www.beatport.com/search?q=Kristian+Heikkila+crisis
https://www.beatport.com/search?q=I+Don%27t+Blame+You++Markus+Homm
https://www.beatport.com/search?q=Undine+Original+MixMilad+Ash%2C+F4T4L3RR0R
all found as release, but also show up as 1st result in track results (at this moment).

even the 2 main examples are found by now:
https://www.beatport.com/search?q=alex+morelli+crimson+idol
https://www.beatport.com/search?q=crazibiza+roller+disco

Regarding 500 vs 1400px cover-wise on the test.rar, I can replicate:
https://beatport.com/track/concept-of-house/14792695
https://beatport.com/track/from-outer-space/14781409
https://beatport.com/track/supernova/14757292
https://beatport.com/track/the-lost-soul/14757295
https://beatport.com/track/prometheus/14845891
have 1400px after tagging , though 500 was set.

while:
https://beatport.com/track/unfold-me/14620850
https://beatport.com/track/space-deep/14695727
https://beatport.com/track/the-rituals/14695723
https://beatport.com/track/4u/14790613
https://beatport.com/track/maori/14781410
https://beatport.com/track/planet/14703502
https://beatport.com/track/the-girl-with-the-rainbow-hat/14738264
https://beatport.com/track/under-the-influence/14738263
those do have 500px after tagging as it should.

Investigation of Marekkon5 will come up tomorrow or so.

One track is not found on v1.1.8, which is correct, since it's not available on Beatport:
https://www.beatport.com/search?q=Michael+Kaelios+-+The+Future+(Extended+Mix)

**Comment by atarbig** [comment]
Yes, it works now. I was really surprised that the exclusive tracks not found in tagger. I've been trying to test these tracks all day. But it's working now.

**Comment by Marekkon5** [comment]
Beatport did some internal changes and is really inconsistent with the album art now, but I tried to make a workaround.

**Comment by Marekkon5** [comment]
Seems like its working properly, will make release soon.
