### ISSUE TITLE
Update performance test results for all taggers

### ISSUE THREAD

**Issue by cromize** [Marekkon5/beatporttagger#5]
Hey, could you update your performance test results spreadsheet? It indeed looks nice.

I've fixed a bug that caused false positives with my tagger. Also note, that [cromize/beatport_tracktagger](https://github.com/cromize/beatport_tracktagger) was originally intended to work only with beatport id included in filename. Fuzzy stuff was added later and it has better results now.

[cromize/beatport_tracktagger](https://github.com/cromize/beatport_tracktagger) could use some nice GUI, though. Next time consider creating pull requests instead!

**Comment by bascurtiz** [comment]
@cromize 
Yo! 
Since it does take a while, since u have to manually review them, and this is more concerned your app than ours,
I suggest u do so yourself. 
I'll link u the tracks in 64kbps [here](https://mega.nz/file/xV4AzL6L#EAyFSlpUpeOlxsmKp4Mkdr9KQUTMYew49wAwzR-W4wU).
When done, feel free, to create a google sheet and share, so i can update the original comparison.
